version: '3.8' #https://docs.docker.com/compose/compose-file/compose-file-v3/
services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres # Pls change this to something more secure
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped # if you change [always | unless-stopped]
    networks:
      - service-network
  ipfs:
    image: ipfs/go-ipfs:latest
    restart: always
    ports:
      - '5001:5001' # web: localhost:5000/webui
    expose:
      - 5001
    volumes:
      - ipfs-data:/var/lib/ipfs/data
    networks:
      - service-network
volumes:
  postgres-data:
  ipfs-data:
networks:
  service-network:
    driver: bridge